version: '3'

services:
  backend:
    image: lemomate-backend
    container_name: lemomate-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lemomate?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - lemomate-network

  frontend:
    image: lemomate-frontend
    container_name: lemomate-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - lemomate-network

networks:
  lemomate-network:
    driver: bridge
